CREATE DATABASE IF NOT EXISTS idarwincore2;
USE idarwincore2;
CREATE TABLE `barcodes` (
  `barcodes` varchar(33) DEFAULT NULL,
  KEY `barcodes` (`barcodes`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `blockedlist` (
  `Family` varchar(255) DEFAULT NULL,
  `ScientificName` varchar(255) DEFAULT NULL,
  `ScientificNameAuthorship` varchar(255) DEFAULT NULL,
  `TaxonID` int(12) DEFAULT NULL,
  KEY `ScientificName` (`ScientificName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `counties` (
  `stateProvince` varchar(32) DEFAULT NULL,
  `county` varchar(32) DEFAULT NULL,
  `fips` int(5) DEFAULT NULL,
  `coordinates` varchar(8192) DEFAULT NULL,
  `coordinates2` varchar(8192) DEFAULT NULL,
  `coordinates3` varchar(8192) DEFAULT NULL,
  `coordinates4` varchar(8192) DEFAULT NULL,
  `coordinates5` varchar(8192) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE `duplicates` (
  `id` int(10) NOT NULL DEFAULT '0',
  `institutionCode` varchar(64) DEFAULT NULL,
  `collectionCode` varchar(64) DEFAULT NULL,
  `ownerInstitutionCode` varchar(255) DEFAULT NULL,
  `basisOfRecord` varchar(32) DEFAULT NULL,
  `occurrenceID` varchar(255) DEFAULT NULL,
  `catalogNumber` varchar(32) DEFAULT NULL,
  `otherCatalogNumbers` varchar(255) DEFAULT NULL,
  `kingdom` varchar(255) DEFAULT NULL,
  `phylum` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `order` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `scientificName` varchar(255) DEFAULT NULL,
  `tidInterpreted` int(10) DEFAULT NULL,
  `scientificNameAuthorship` varchar(255) DEFAULT NULL,
  `genus` varchar(255) DEFAULT NULL,
  `specificEpithet` varchar(255) DEFAULT NULL,
  `taxonRank` varchar(255) DEFAULT NULL,
  `infraspecificEpithet` varchar(255) DEFAULT NULL,
  `identifiedBy` varchar(255) DEFAULT NULL,
  `dateIdentified` varchar(45) DEFAULT NULL,
  `identificationReferences` text,
  `identificationRemarks` text,
  `taxonRemarks` text,
  `identificationQualifier` varchar(255) DEFAULT NULL,
  `typeStatus` varchar(255) DEFAULT NULL,
  `recordedBy` varchar(255) DEFAULT NULL,
  `recordedByID` int(10) DEFAULT NULL,
  `associatedCollectors` varchar(255) DEFAULT NULL,
  `recordNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `occurrenceRemarks` text,
  `habitat` text,
  `substrate` varchar(255) NOT NULL,
  `verbatimAttributes` varchar(255) DEFAULT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `informationWithheld` varchar(250) DEFAULT NULL,
  `dataGeneralizations` varchar(250) DEFAULT NULL,
  `dynamicProperties` text,
  `associatedTaxa` text,
  `reproductiveCondition` varchar(255) DEFAULT NULL,
  `establishmentMeans` varchar(45) DEFAULT NULL,
  `cultivationStatus` varchar(255) DEFAULT NULL,
  `lifeStage` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `individualCount` varchar(45) DEFAULT NULL,
  `samplingProtocol` varchar(100) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `preparations` varchar(100) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `stateProvince` varchar(255) DEFAULT NULL,
  `county` varchar(64) DEFAULT NULL,
  `municipality` varchar(255) DEFAULT NULL,
  `locality` text,
  `locationRemarks` varchar(255) DEFAULT NULL,
  `localitySecurity` varchar(255) DEFAULT NULL,
  `localitySecurityReason` varchar(255) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) DEFAULT NULL,
  `footprintWKT` text,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferenceProtocol` varchar(255) DEFAULT NULL,
  `georeferenceSources` varchar(255) DEFAULT NULL,
  `georeferenceVerificationStatus` varchar(32) DEFAULT NULL,
  `georeferenceRemarks` varchar(255) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `minimumDepthInMeters` int(10) DEFAULT NULL,
  `maximumDepthinMeters` int(10) DEFAULT NULL,
  `verbatimDepth` int(10) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `disposition` varchar(100) DEFAULT NULL,
  `language` varchar(20) DEFAULT NULL,
  `genericcolumn1` varchar(255) DEFAULT NULL,
  `genericcolumn2` varchar(255) DEFAULT NULL,
  `storageLocation` varchar(255) DEFAULT NULL,
  `observerUid` int(10) DEFAULT NULL,
  `processingStatus` varchar(255) DEFAULT NULL,
  `duplicateQuantity` int(10) DEFAULT NULL,
  `recordEnteredBy` varchar(255) DEFAULT NULL,
  `dateEntered` datetime DEFAULT NULL,
  `dateLastModified` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `sourcePrimaryKey` varchar(255) DEFAULT NULL,
  `recordId` int(10) DEFAULT NULL,
  `references` text,
  KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `identifications` (
  `coreid` int(10) DEFAULT NULL,
  `identifiedBy` varchar(255) DEFAULT NULL,
  `IdentifiedByID` int(10) DEFAULT NULL,
  `dateIdentified` date DEFAULT NULL,
  `identificationQualifier` varchar(255) DEFAULT NULL,
  `scientificName` varchar(255) DEFAULT NULL,
  `tidInterpreted` varchar(255) DEFAULT NULL,
  `identificationIsCurrent` int(10) DEFAULT NULL,
  `scientificNameAuthorship` varchar(255) DEFAULT NULL,
  `genus` varchar(255) DEFAULT NULL,
  `specificEpithet` varchar(255) DEFAULT NULL,
  `taxonRank` int(10) DEFAULT NULL,
  `infraspecificEpithet` varchar(255) DEFAULT NULL,
  `identificationReferences` varchar(255) DEFAULT NULL,
  `identificationRemarks` varchar(255) DEFAULT NULL,
  `recordID` int(10) DEFAULT NULL,
  `modified` date DEFAULT NULL,
  KEY `coreid` (`coreid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `images` (
  `coreid` int(10) DEFAULT NULL,
  `identifier` varchar(255) DEFAULT NULL,
  `accessURI` varchar(255) DEFAULT NULL,
  `thumbnailAccessURI` varchar(255) DEFAULT NULL,
  `goodQualityAccessURI` varchar(255) DEFAULT NULL,
  `rights` varchar(255) DEFAULT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `comments` text,
  `providerManagedID` varchar(255) DEFAULT NULL,
  `MetadataDate` varchar(255) DEFAULT NULL,
  `format` varchar(255) DEFAULT NULL,
  `associatedSpecimenReference` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `subtype` varchar(255) DEFAULT NULL,
  `metadataLanguage` varchar(255) DEFAULT NULL,
  KEY `coreid` (`coreid`),
  KEY `identifier` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `iplant` (
  `guid` varchar(33) DEFAULT NULL,
  `ifile` varchar(255) DEFAULT NULL,
  `barcode` varchar(15) DEFAULT NULL,
  KEY `guid` (`guid`),
  KEY `barcode` (`barcode`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `measurementorfact` (
  `coreid` int(11) NOT NULL,
  `measurementType` varchar(256) DEFAULT NULL,
  `measurementTypeID` text,
  `measurementValue` text,
  `measurementValueID` text,
  `measurementUnit` varchar(256) DEFAULT NULL,
  `measurementDeterminedDate` datetime DEFAULT NULL,
  `measurementDeterminedBy` text,
  `measurementRemarks` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `ndrive` (
  `file` varchar(255) DEFAULT NULL,
  `ncatalogNumber` varchar(16) DEFAULT NULL,
  KEY `ncatalogNumber` (`ncatalogNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `noskeletalrecords` (
  `id` int(10) NOT NULL DEFAULT '0',
  `institutionCode` varchar(64) DEFAULT NULL,
  `collectionCode` varchar(64) DEFAULT NULL,
  `ownerInstitutionCode` varchar(255) DEFAULT NULL,
  `basisOfRecord` varchar(32) DEFAULT NULL,
  `occurrenceID` varchar(255) DEFAULT NULL,
  `catalogNumber` varchar(32) DEFAULT NULL,
  `otherCatalogNumbers` varchar(255) DEFAULT NULL,
  `kingdom` varchar(255) DEFAULT NULL,
  `phylum` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `order` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `scientificName` varchar(255) DEFAULT NULL,
  `tidInterpreted` int(10) DEFAULT NULL,
  `scientificNameAuthorship` varchar(255) DEFAULT NULL,
  `genus` varchar(255) DEFAULT NULL,
  `specificEpithet` varchar(255) DEFAULT NULL,
  `taxonRank` varchar(255) DEFAULT NULL,
  `infraspecificEpithet` varchar(255) DEFAULT NULL,
  `identifiedBy` varchar(255) DEFAULT NULL,
  `dateIdentified` varchar(45) DEFAULT NULL,
  `identificationReferences` text,
  `identificationRemarks` text,
  `taxonRemarks` text,
  `identificationQualifier` varchar(255) DEFAULT NULL,
  `typeStatus` varchar(255) DEFAULT NULL,
  `recordedBy` varchar(255) DEFAULT NULL,
  `recordedByID` int(10) DEFAULT NULL,
  `associatedCollectors` varchar(255) DEFAULT NULL,
  `recordNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `occurrenceRemarks` text,
  `habitat` text,
  `substrate` varchar(255) NOT NULL,
  `verbatimAttributes` varchar(255) DEFAULT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `informationWithheld` varchar(250) DEFAULT NULL,
  `dataGeneralizations` varchar(250) DEFAULT NULL,
  `dynamicProperties` text,
  `associatedTaxa` text,
  `reproductiveCondition` varchar(255) DEFAULT NULL,
  `establishmentMeans` varchar(45) DEFAULT NULL,
  `cultivationStatus` varchar(255) DEFAULT NULL,
  `lifeStage` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `individualCount` varchar(45) DEFAULT NULL,
  `samplingProtocol` varchar(100) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `preparations` varchar(100) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `stateProvince` varchar(255) DEFAULT NULL,
  `county` varchar(64) DEFAULT NULL,
  `municipality` varchar(255) DEFAULT NULL,
  `locality` text,
  `locationRemarks` varchar(255) DEFAULT NULL,
  `localitySecurity` varchar(255) DEFAULT NULL,
  `localitySecurityReason` varchar(255) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) DEFAULT NULL,
  `footprintWKT` text,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferenceProtocol` varchar(255) DEFAULT NULL,
  `georeferenceSources` varchar(255) DEFAULT NULL,
  `georeferenceVerificationStatus` varchar(32) DEFAULT NULL,
  `georeferenceRemarks` varchar(255) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `minimumDepthInMeters` int(10) DEFAULT NULL,
  `maximumDepthinMeters` int(10) DEFAULT NULL,
  `verbatimDepth` int(10) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `disposition` varchar(100) DEFAULT NULL,
  `language` varchar(20) DEFAULT NULL,
  `genericcolumn1` varchar(255) DEFAULT NULL,
  `genericcolumn2` varchar(255) DEFAULT NULL,
  `storageLocation` varchar(255) DEFAULT NULL,
  `observerUid` int(10) DEFAULT NULL,
  `processingStatus` varchar(255) DEFAULT NULL,
  `duplicateQuantity` int(10) DEFAULT NULL,
  `recordEnteredBy` varchar(255) DEFAULT NULL,
  `dateEntered` datetime DEFAULT NULL,
  `dateLastModified` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `sourcePrimaryKey` varchar(255) DEFAULT NULL,
  `recordId` int(10) DEFAULT NULL,
  `references` text,
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE `occurrences` (
  `id` int(10) NOT NULL DEFAULT '0',
  `institutionCode` varchar(64) DEFAULT NULL,
  `collectionCode` varchar(64) DEFAULT NULL,
  `ownerInstitutionCode` varchar(255) DEFAULT NULL,
  `basisOfRecord` varchar(32) DEFAULT NULL,
  `occurrenceID` varchar(255) DEFAULT NULL,
  `catalogNumber` varchar(32) DEFAULT NULL,
  `otherCatalogNumbers` varchar(255) DEFAULT NULL,
  `kingdom` varchar(255) DEFAULT NULL,
  `phylum` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `order` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `scientificName` varchar(255) DEFAULT NULL,
  `tidInterpreted` int(10) DEFAULT NULL,
  `scientificNameAuthorship` varchar(255) DEFAULT NULL,
  `genus` varchar(255) DEFAULT NULL,
  `specificEpithet` varchar(255) DEFAULT NULL,
  `taxonRank` varchar(255) DEFAULT NULL,
  `infraspecificEpithet` varchar(255) DEFAULT NULL,
  `identifiedBy` varchar(255) DEFAULT NULL,
  `dateIdentified` varchar(45) DEFAULT NULL,
  `identificationReferences` text,
  `identificationRemarks` text,
  `taxonRemarks` text,
  `identificationQualifier` varchar(255) DEFAULT NULL,
  `typeStatus` varchar(255) DEFAULT NULL,
  `recordedBy` varchar(255) DEFAULT NULL,
  `recordedByID` int(10) DEFAULT NULL,
  `associatedCollectors` varchar(255) DEFAULT NULL,
  `recordNumber` varchar(45) DEFAULT NULL,
  `eventDate` date DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `startDayOfYear` int(10) DEFAULT NULL,
  `endDayOfYear` int(10) DEFAULT NULL,
  `verbatimEventDate` varchar(255) DEFAULT NULL,
  `occurrenceRemarks` text,
  `habitat` text,
  `substrate` varchar(255) NOT NULL,
  `verbatimAttributes` varchar(255) DEFAULT NULL,
  `fieldNumber` varchar(45) DEFAULT NULL,
  `informationWithheld` varchar(250) DEFAULT NULL,
  `dataGeneralizations` varchar(250) DEFAULT NULL,
  `dynamicProperties` text,
  `associatedTaxa` text,
  `reproductiveCondition` varchar(255) DEFAULT NULL,
  `establishmentMeans` varchar(45) DEFAULT NULL,
  `cultivationStatus` varchar(255) DEFAULT NULL,
  `lifeStage` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `individualCount` varchar(45) DEFAULT NULL,
  `samplingProtocol` varchar(100) DEFAULT NULL,
  `samplingEffort` varchar(200) DEFAULT NULL,
  `preparations` varchar(100) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `stateProvince` varchar(255) DEFAULT NULL,
  `county` varchar(64) DEFAULT NULL,
  `municipality` varchar(255) DEFAULT NULL,
  `locality` text,
  `locationRemarks` varchar(255) DEFAULT NULL,
  `localitySecurity` varchar(255) DEFAULT NULL,
  `localitySecurityReason` varchar(255) DEFAULT NULL,
  `decimalLatitude` double DEFAULT NULL,
  `decimalLongitude` double DEFAULT NULL,
  `geodeticDatum` varchar(255) DEFAULT NULL,
  `coordinateUncertaintyInMeters` int(10) DEFAULT NULL,
  `footprintWKT` text,
  `verbatimCoordinates` varchar(255) DEFAULT NULL,
  `georeferencedBy` varchar(255) DEFAULT NULL,
  `georeferenceProtocol` varchar(255) DEFAULT NULL,
  `georeferenceSources` varchar(255) DEFAULT NULL,
  `georeferenceVerificationStatus` varchar(32) DEFAULT NULL,
  `georeferenceRemarks` varchar(255) DEFAULT NULL,
  `minimumElevationInMeters` int(6) DEFAULT NULL,
  `maximumElevationInMeters` int(6) DEFAULT NULL,
  `minimumDepthInMeters` int(10) DEFAULT NULL,
  `maximumDepthinMeters` int(10) DEFAULT NULL,
  `verbatimDepth` int(10) DEFAULT NULL,
  `verbatimElevation` varchar(255) DEFAULT NULL,
  `disposition` varchar(100) DEFAULT NULL,
  `language` varchar(20) DEFAULT NULL,
  `genericcolumn1` varchar(255) DEFAULT NULL,
  `genericcolumn2` varchar(255) DEFAULT NULL,
  `storageLocation` varchar(255) DEFAULT NULL,
  `observerUid` int(10) DEFAULT NULL,
  `processingStatus` varchar(255) DEFAULT NULL,
  `duplicateQuantity` int(10) DEFAULT NULL,
  `recordEnteredBy` varchar(255) DEFAULT NULL,
  `dateEntered` datetime DEFAULT NULL,
  `dateLastModified` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `sourcePrimaryKey` varchar(255) DEFAULT NULL,
  `recordId` int(10) DEFAULT NULL,
  `references` text,
  KEY `id` (`id`),
  KEY `catalogNumber` (`catalogNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;